"""
text_to_sql_generator.py

LLM-powered Text-to-SQL Generator (Fallback untuk pattern-based)
Dipanggil HANYA jika pattern matching gagal
"""

import requests
import json
import re
from database_schema import get_complete_schema_for_llm, get_allowed_tables


def generate_sql_with_llm(
    query: str,
    context: dict,
    ollama_url: str = "http://116.193.191.185:11434",
    model: str = "llama3.1:8b"
) -> dict:
    """
    Generate SQL menggunakan LLM (fallback dari pattern-based)
    
    Returns:
        {
            'success': bool,
            'sql': str,
            'confidence': float,
            'reasoning': str
        }
    """
    
    try:
        print("\n" + "=" * 60)
        print("🤖 LLM SQL GENERATION (FALLBACK MODE)")
        print("=" * 60)
        print(f"Query: {query}")
        print(f"Context: {context}")
        print("=" * 60)
        
        # Build prompt dengan schema lengkap
        prompt = build_text_to_sql_prompt(query, context)
        
        # Call Ollama
        response = requests.post(
            f"{ollama_url}/api/generate",
            json={
                "model": model,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.1,  # Very low untuk SQL generation
                    "top_p": 0.9,
                    "top_k": 40,
                    "num_predict": 256,
                }
            },
            timeout=120  # SQL generation harus cepat
        )
        
        if response.status_code != 200:
            return {
                'success': False,
                'error': f"Ollama API error: {response.status_code}"
            }
        
        result = response.json()
        llm_output = result.get('response', '').strip()
        
        print(f"\n🤖 LLM Output:\n{llm_output}\n")
        
        # Extract SQL dari output LLM
        sql = extract_sql_from_llm_output(llm_output)
        
        if not sql:
            print("❌ Failed to extract SQL from LLM output")
            return {
                'success': False,
                'error': 'Could not extract valid SQL from LLM response'
            }
        
        # Validate SQL
        validation = validate_sql_query(sql)
        
        if not validation['valid']:
            print(f"❌ SQL validation failed: {validation['reason']}")
            return {
                'success': False,
                'error': f"Generated SQL is invalid: {validation['reason']}"
            }
        
        print(f"✅ LLM Generated SQL:\n{sql}\n")
        print("=" * 60)
        
        return {
            'success': True,
            'sql': sql,
            'confidence': 0.8,  # LLM-generated confidence
            'reasoning': 'Generated by LLM (fallback from pattern matching)',
            'source': 'llm'
        }
        
    except Exception as e:
        print(f"❌ LLM SQL generation error: {str(e)}")
        import traceback
        traceback.print_exc()
        
        return {
            'success': False,
            'error': str(e)
        }


def build_text_to_sql_prompt(query: str, context: dict) -> str:
    """Build prompt MINIMAL - hanya tabel yang dibutuhkan"""
    
    # Extract context
    nojar = context.get('last_nojar', '')
    spk = context.get('last_spk', '')
    
    # ✅ MINIMAL SCHEMA - Bukan full schema!
    schema_text = """=== DATABASE SCHEMA (MINIMAL) ===

📊 TABLE: spk (Surat Perintah Kerja)
   • id_spk (BIGINT) [PRIMARY KEY]
   • no_spk (VARCHAR) [UNIQUE] - Format: 065848/WO-LA/2021
   • no_jaringan (VARCHAR) [FOREIGN KEY] - 10 digit
   • jenis_spk (ENUM) - aktivasi, dismantle, instalasi, survey, maintenance
   • tanggal_spk (DATE)
   • is_deleted (BOOLEAN)
   ⚠️ WAJIB: WHERE is_deleted = 0

📊 TABLE: jaringan (Data Pelanggan)
   • no_jaringan (VARCHAR) [PRIMARY KEY] - 10 digit
   • nama_pelanggan (VARCHAR)
   • lokasi_pelanggan (TEXT)
   • pop (TEXT) - Point of Presence
   • jasa (VARCHAR)
   • kecepatan (VARCHAR)
   • tgl_rfs_la (DATE)
   • is_deleted (BOOLEAN)
   ⚠️ WAJIB: WHERE is_deleted = 0

📊 TABLE: spk_execution_info (Teknisi & Vendor)
   • id_spk (BIGINT) [FOREIGN KEY]
   • teknisi (VARCHAR)
   • nama_vendor (VARCHAR)
   • pic_pelanggan (VARCHAR)
   
🔗 RELATIONSHIPS:
   spk.no_jaringan → jaringan.no_jaringan (MANY-to-ONE)
   spk_execution_info.id_spk → spk.id_spk (ONE-to-ONE, use LEFT JOIN)

📝 EXAMPLE QUERIES:
   COUNT: SELECT COUNT(*) as jumlah_spk FROM spk WHERE no_jaringan = 'X' AND is_deleted = 0
   LIST: SELECT s.no_spk, s.jenis_spk, s.tanggal_spk FROM spk s WHERE no_jaringan = 'X' AND is_deleted = 0
   JOIN: SELECT s.*, j.nama_pelanggan, sei.teknisi FROM spk s JOIN jaringan j ON s.no_jaringan = j.no_jaringan LEFT JOIN spk_execution_info sei ON s.id_spk = sei.id_spk WHERE s.no_spk = 'X'
"""
    
    # Context info
    context_info = ""
    if nojar:
        context_info += f"\n- Nomor Jaringan: {nojar}"
    if spk:
        context_info += f"\n- SPK: {spk}"
    
    # ✅ MINIMAL PROMPT - No examples, no verbose
    prompt = f"""{schema_text}

=== CONTEXT ==={context_info if context_info else "(No context)"}

=== RULES ===
1. Output ONLY SQL (no explanation)
2. ALWAYS add "AND is_deleted = 0" for spk/jaringan
3. Use LEFT JOIN for spk_execution_info
4. ORDER BY tanggal_spk DESC for lists

USER QUERY: "{query}"

SQL:"""
    
    return prompt


def extract_sql_from_llm_output(llm_output: str) -> str:
    """
    Extract SQL query dari output LLM
    Menghapus markdown, code blocks, dan noise lainnya
    """
    
    # Remove markdown code blocks
    sql = re.sub(r'```sql\s*', '', llm_output, flags=re.IGNORECASE)
    sql = re.sub(r'```\s*', '', sql)
    
    # Remove common prefixes
    prefixes = [
        'SQL QUERY:', 'Query:', 'Here is the query:', 'Here is the SQL:',
        'The SQL query is:', 'SQL:', 'Answer:'
    ]
    for prefix in prefixes:
        sql = re.sub(rf'^{re.escape(prefix)}\s*', '', sql, flags=re.IGNORECASE)
    
    # Extract only SELECT statement
    # Find first SELECT and last semicolon (or end of string)
    match = re.search(r'(SELECT\b.*?(?:;|$))', sql, re.IGNORECASE | re.DOTALL)
    if match:
        sql = match.group(1)
    
    # Clean up
    sql = sql.strip()
    sql = sql.rstrip(';')  # Remove trailing semicolon for consistency
    
    # Validate starts with SELECT
    if not sql.upper().startswith('SELECT'):
        return ""
    
    return sql


def validate_sql_query(sql: str) -> dict:
    """
    Validate SQL query untuk security dan correctness
    
    Returns:
        {'valid': bool, 'reason': str}
    """
    
    sql_upper = sql.upper().strip()
    
    # Rule 1: Must start with SELECT
    if not sql_upper.startswith('SELECT'):
        return {'valid': False, 'reason': 'Query must start with SELECT'}
    
    # Rule 2: Forbidden commands
    forbidden = [
        'DROP', 'DELETE', 'UPDATE', 'INSERT', 'ALTER', 'TRUNCATE',
        'EXEC', 'EXECUTE', 'LOAD_FILE', 'OUTFILE', 'DUMPFILE',
        'GRANT', 'REVOKE', 'CREATE', 'REPLACE'
    ]
    
    for cmd in forbidden:
        if cmd in sql_upper:
            return {'valid': False, 'reason': f'Forbidden command: {cmd}'}
    
    # Rule 3: Must have FROM clause
    if 'FROM' not in sql_upper:
        return {'valid': False, 'reason': 'Query must have FROM clause'}
    
    # Rule 4: Must use allowed tables
    allowed_tables = get_allowed_tables()
    has_valid_table = False
    
    for table in allowed_tables:
        if table.upper() in sql_upper:
            has_valid_table = True
            break
    
    if not has_valid_table:
        return {'valid': False, 'reason': 'Query must use valid tables from schema'}
    
    # Rule 5: Check for is_deleted filter (for spk and jaringan tables)
    if 'SPK' in sql_upper and 'IS_DELETED' not in sql_upper:
        return {'valid': False, 'reason': 'SPK queries must include is_deleted filter'}
    
    if 'JARINGAN' in sql_upper and 'IS_DELETED' not in sql_upper:
        return {'valid': False, 'reason': 'JARINGAN queries must include is_deleted filter'}
    
    return {'valid': True, 'reason': 'Valid'}


# ============================================
# TESTING
# ============================================

if __name__ == "__main__":
    # Test dengan beberapa query
    test_queries = [
        {
            'query': 'pop nya apa?',
            'context': {'last_nojar': '2023390898'}
        },
        {
            'query': 'siapa teknisi yang menangani spk survey?',
            'context': {'last_nojar': '2023390898'}
        },
        {
            'query': 'ada berapa spk maintenance?',
            'context': {'last_nojar': '2021242440'}
        }
    ]
    
    for test in test_queries:
        print("\n" + "=" * 80)
        print(f"Testing: {test['query']}")
        print(f"Context: {test['context']}")
        print("=" * 80)
        
        result = generate_sql_with_llm(
            query=test['query'],
            context=test['context']
        )
        
        print("\n📊 Result:")
        print(json.dumps(result, indent=2, ensure_ascii=False))
        print("=" * 80)