"""
Config Package
Taruh file ini di: parsers/config/__init__.py
"""

from .labels import (
    INFORMASI_GEDUNG_LABELS,
    SARPEN_LABELS,
    LOKASI_ANTENA_LABELS,
    PERIZINAN_BIAYA_GEDUNG_LABELS,
    PENEMPATAN_PERANGKAT_LABELS,
    PERIZINAN_BIAYA_KAWASAN_LABELS,
    KAWASAN_UMUM_LABELS,
    DATA_SPLITTER_LABELS,
)

__all__ = [
    'INFORMASI_GEDUNG_LABELS',
    'SARPEN_LABELS',
    'LOKASI_ANTENA_LABELS',
    'PERIZINAN_BIAYA_GEDUNG_LABELS',
    'PENEMPATAN_PERANGKAT_LABELS',
    'PERIZINAN_BIAYA_KAWASAN_LABELS',
    'KAWASAN_UMUM_LABELS',
    'DATA_SPLITTER_LABELS',
]